In [1]:
from __future__ import print_function
import torch

# 张量初探

In [2]:
#创建一个未初始化矩阵
#x = torch.Tensor(5,3).int()
#print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [3]:
#创建一个初始化矩阵
x = torch.rand(5,3)
y = torch.rand(5,3)
print(y)

tensor([[0.9593, 0.3420, 0.7913],
        [0.5408, 0.6195, 0.0108],
        [0.5666, 0.5060, 0.0214],
        [0.3867, 0.0533, 0.2909],
        [0.1372, 0.8211, 0.5039]])


In [5]:
#获取矩阵大小
print(x.size())

torch.Size([5, 3])


注意：torch.Size实际上是一个元组，所以它支持元组相同的操作。

# 张量的各种操作运算

In [7]:
#加法
a = torch.add(x,y)
print(a)

tensor([[1.9010, 0.9944, 1.5574],
        [0.8631, 0.8097, 0.6377],
        [0.5883, 0.8026, 0.8393],
        [0.5593, 0.9419, 0.4984],
        [0.5423, 0.8239, 1.3167]])


In [8]:
#把x加到y上
y.add_(x)
print(y)

tensor([[1.9010, 0.9944, 1.5574],
        [0.8631, 0.8097, 0.6377],
        [0.5883, 0.8026, 0.8393],
        [0.5593, 0.9419, 0.4984],
        [0.5423, 0.8239, 1.3167]])


Note:任何在原地(in-place)改变张量的操作都有一个’_’后缀。例如x.copy_(y), x.t_()操作将改变x.

你可以使用所有的numpy索引操作。

In [10]:
print(x)
print(x[:,1])

tensor([[0.9417, 0.6524, 0.7661],
        [0.3223, 0.1901, 0.6270],
        [0.0216, 0.2966, 0.8179],
        [0.1725, 0.8887, 0.2075],
        [0.4050, 0.0029, 0.8128]])
tensor([0.6524, 0.1901, 0.2966, 0.8887, 0.0029])


# Numpy
把一个torch张量转换为numpy数组或者反过来都是很简单的。

Torch张量和numpy数组将共享潜在的内存，改变其中一个也将改变另一个。

In [15]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [16]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [18]:
#把numpy数组转换为张量
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [21]:
#CUDA张量
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))